name = "MyFirstPackage"
uuid = "3ecf1533-fdf7-4562-b419-576cda0c0069"
authors = ["zhangdezheng"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
